[[OSQP_MKL]]
arch = "x86_64"
git-tree-sha1 = "7c8fa945135739cca4e97208fbc3a06cf24f4b53"
libc = "glibc"
os = "linux"

    [[OSQP_MKL.download]]
    sha256 = "c77be8ecf6e7fb109fa60c333f000d627d32690f68ccc261c71a8382f220a0a3"
    url = "https://github.com/osqp/OSQP_MKL_jll.jl/releases/download/OSQP_MKL-v100.0.0+0/OSQP_MKL.v100.0.0.x86_64-linux-gnu.tar.gz"
