[[OSQP_MKL]]
arch = "x86_64"
git-tree-sha1 = "3a3ca04da6b578f411aa4cc01eab81e7e3b51431"
libc = "glibc"
os = "linux"

    [[OSQP_MKL.download]]
    sha256 = "b96ab99e783a2219689132abfa6be408563d7d77e60da8d90c9b810732f4eaca"
    url = "https://github.com/osqp/OSQP_MKL_jll.jl/releases/download/OSQP_MKL-v100.0.0+0/OSQP_MKL.v100.0.0.x86_64-linux-gnu.tar.gz"
