# Autogenerated wrapper script for OSQP_MKL_jll for x86_64-apple-darwin
export osqp_mkl

using MKL_jll
JLLWrappers.@generate_wrapper_header("OSQP_MKL")
JLLWrappers.@declare_library_product(osqp_mkl, "@rpath/libosqp_mkl.dylib")
function __init__()
    JLLWrappers.@generate_init_header(MKL_jll)
    JLLWrappers.@init_library_product(
        osqp_mkl,
        "lib/libosqp_mkl.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
